### ISSUE TITLE
This ticket has been separated into 4.1 and 4.2 ****HR should be able to edit an employee

### ISSUE THREAD

**Issue by askingalot** [nss-crystal-cobras/WorkforceManagement#4]
## Acceptance Criteria

**Given** user is viewing an employee
**When** user clicks on the Edit link
**Then** user should be able to edit the last name of the employee
**Or** change the department to which the employee is assigned
**Or** change the computer assigned to the employee
**Or** add/remove training programs for the employee to attend in the future

**Comment by loetek** [comment]
Under the advisement of Senior Developer, this ticket was separated into two tickets.
